In [1]:
from urllib.request import urlopen
import json
import os

import numpy as np
import pandas as pd

import csv
# import plotly.express as px
# import plotly.graph_objects as go  # or plotly.express as px

# from .about_us import about_us_html

In [3]:
census_data = pd.read_csv('../data/2019-census-all.csv', sep = ',')

In [7]:
describe_census = census_data.describe()

,SUMLEV,STATE,COUNTY,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,WA_MALE,WA_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
count,716376.0,716376.000000,716376.000000,716376.000000,716376.000000,7.163760e+05,7.163760e+05,7.163760e+05,7.163760e+05,7.163760e+05,...,7.163760e+05,7.163760e+05,716376.000000,716376.000000,716376.000000,716376.000000,716376.000000,716376.000000,716376.000000,716376.000000
mean,50.0,30.280076,103.572884,6.500000,9.000000,1.063685e+04,5.234179e+03,5.402668e+03,4.080277e+03,4.158328e+03,...,8.438406e+02,8.227857e+02,54.235452,56.398190,39.464714,37.060898,16.377508,16.472897,5.873270,5.625510
std,0.0,15.141940,107.686994,3.452055,5.477229,7.941355e+04,3.901866e+04,4.040807e+04,2.855301e+04,2.886512e+04,...,1.355657e+04,1.357119e+04,762.910366,846.267395,531.608379,510.789526,289.816196,293.717292,102.577871,102.219707
min,50.0,1.000000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50.0,18.000000,35.000000,3.750000,4.000000,5.850000e+02,2.840000e+02,2.970000e+02,2.380000e+02,2.470000e+02,...,5.000000e+00,4.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,50.0,29.000000,79.000000,6.500000,9.000000,1.490000e+03,7.370000e+02,7.510000e+02,6.260000e+02,6.450000e+02,...,2.200000e+01,1.900000e+01,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,50.0,45.000000,133.000000,9.250000,14.000000,4.462000e+03,2.201000e+03,2.262000e+03,1.886000e+03,1.929000e+03,...,1.280000e+02,1.150000e+02,7.000000,6.000000,8.000000,7.000000,2.000000,2.000000,1.000000,1.000000
max,50.0,56.000000,840.000000,12.000000,18.000000,1.010571e+07,4.980981e+06,5.125335e+06,3.593116e+06,3.588091e+06,...,2.288151e+06,2.300374e+06,110432.000000,127608.000000,85965.000000,82360.000000,50549.000000,50659.000000,17420.000000,17072.000000